# Auto-generated by BBReborneDIYTool.ps1
# Dot-source this file to reuse the paths:
#   . "C:\Path\To\BBReborneDIYTool.paths.ps1"

$BBR_GameRoot = 'C:\Users\Sero\Documents\bbtemp1\bb_og\CUSA00900\dvdroot_ps4'
$BBR_OutputRoot = 'C:\Users\Sero\Desktop\testm'
$BBR_ToolDownloadDir = 'C:\Users\Sero\BBReborneDIYTool\_downloads'
$BBR_ToolRoot = 'C:\Users\Sero\BBReborneDIYTool\Tools'
$BBR_CpuThrottle = 30
$BBR_GpuThrottle = 2
$BBR_LogicalProcessors = '32'
$BBR_CpuInfo = 'AMD Ryzen 9 9950X3D 16-Core Processor'
$BBR_GpuInfo = 'GPU detection unavailable'
$BBR_GpuVram = '31.8 GB highest detected'

$BBR_Pwsh7Exe = 'C:\Program Files\PowerShell\7\pwsh.exe'
$env:BBR_Pwsh7Exe = $BBR_Pwsh7Exe
$BBR_DotNetExe = 'C:\Program Files\dotnet\dotnet.exe'
$env:BBR_DotNetExe = $BBR_DotNetExe
$BBR_WitchyBND_v3_0_0_1 = 'C:\Users\Sero\BBReborneDIYTool\Tools\WitchyBND\WitchyBND-v3.0.0.1-win-x64\WitchyBND.exe'
$env:BBR_WitchyBND_v3_0_0_1 = $BBR_WitchyBND_v3_0_0_1
$BBR_WitchyBND_v2_14_4_5 = 'C:\Users\Sero\BBReborneDIYTool\Tools\WitchyBND\WitchyBND-v2.14.4.5\WitchyBND.exe'
$env:BBR_WitchyBND_v2_14_4_5 = $BBR_WitchyBND_v2_14_4_5
$BBR_WitchyBND_v2_4_0_1 = 'C:\Users\Sero\BBReborneDIYTool\Tools\WitchyBND\WitchyBND-v2.4.0.1\WitchyBND.exe'
$env:BBR_WitchyBND_v2_4_0_1 = $BBR_WitchyBND_v2_4_0_1
$BBR_ImageMagickExe = 'C:\Program Files\ImageMagick-7.1.2-Q16-HDRI\magick.exe'
$env:BBR_ImageMagickExe = $BBR_ImageMagickExe
$BBR_TexconvExe = 'C:\Users\Sero\BBReborneDIYTool\Tools\DirectXTex\texconv.exe'
$env:BBR_TexconvExe = $BBR_TexconvExe
$BBR_RealEsrganExe = 'C:\Users\Sero\BBReborneDIYTool\Tools\RealESRGAN\realesrgan-ncnn-vulkan-20220424-windows\realesrgan-ncnn-vulkan.exe'
$env:BBR_RealEsrganExe = $BBR_RealEsrganExe
$BBR_GitExe = 'C:\Program Files\Git\cmd\git.exe'
$env:BBR_GitExe = $BBR_GitExe
$BBR_BtabJsonToolExe = 'C:\Users\Sero\BBReborneDIYTool\Tools\BtabJsonTool\bin\Release\net9.0\BtabJsonTool.exe'
$env:BBR_BtabJsonToolExe = $BBR_BtabJsonToolExe
$BBR_BtlJsonToolExe = 'C:\Users\Sero\BBReborneDIYTool\Tools\BtlJsonTool\bin\Release\net9.0\BtlJsonTool.exe'
$env:BBR_BtlJsonToolExe = $BBR_BtlJsonToolExe
$BBR_BtpbJsonToolExe = 'C:\Users\Sero\BBReborneDIYTool\Tools\BtpbJsonTool\bin\Release\net9.0\BtpbJsonTool.exe'
$env:BBR_BtpbJsonToolExe = $BBR_BtpbJsonToolExe
$BBR_DCXToolExe = 'C:\Users\Sero\BBReborneDIYTool\Tools\DCXTool\bin\Release\net9.0\DCXTool.exe'
$env:BBR_DCXToolExe = $BBR_DCXToolExe
$BBR_FlverJsonToolExe = 'C:\Users\Sero\BBReborneDIYTool\Tools\FlverJsonTool\bin\Release\net9.0\FlverJsonTool.exe'
$env:BBR_FlverJsonToolExe = $BBR_FlverJsonToolExe
$BBR_FxrJsonToolExe = 'C:\Users\Sero\BBReborneDIYTool\Tools\FxrJsonTool\bin\Release\net9.0\FxrJsonTool.exe'
$env:BBR_FxrJsonToolExe = $BBR_FxrJsonToolExe
$BBR_MsbbJsonToolExe = 'C:\Users\Sero\BBReborneDIYTool\Tools\MsbbJsonTool\bin\Release\net9.0\MsbbJsonTool.exe'
$env:BBR_MsbbJsonToolExe = $BBR_MsbbJsonToolExe
$BBR_NvaJsonToolExe = 'C:\Users\Sero\BBReborneDIYTool\Tools\NvaJsonTool\bin\Release\net9.0\NvaJsonTool.exe'
$env:BBR_NvaJsonToolExe = $BBR_NvaJsonToolExe

$BBR_Tools = [ordered]@{
    'PowerShell 7' = 'C:\Program Files\PowerShell\7\pwsh.exe'
    '.NET 9 SDK' = 'C:\Program Files\dotnet\dotnet.exe'
    'WitchyBND v3.0.0.1' = 'C:\Users\Sero\BBReborneDIYTool\Tools\WitchyBND\WitchyBND-v3.0.0.1-win-x64\WitchyBND.exe'
    'WitchyBND v2.14.4.5' = 'C:\Users\Sero\BBReborneDIYTool\Tools\WitchyBND\WitchyBND-v2.14.4.5\WitchyBND.exe'
    'WitchyBND v2.4.0.1' = 'C:\Users\Sero\BBReborneDIYTool\Tools\WitchyBND\WitchyBND-v2.4.0.1\WitchyBND.exe'
    'ImageMagick Q16-HDRI' = 'C:\Program Files\ImageMagick-7.1.2-Q16-HDRI\magick.exe'
    'texconv.exe' = 'C:\Users\Sero\BBReborneDIYTool\Tools\DirectXTex\texconv.exe'
    'Real-ESRGAN ncnn Vulkan' = 'C:\Users\Sero\BBReborneDIYTool\Tools\RealESRGAN\realesrgan-ncnn-vulkan-20220424-windows\realesrgan-ncnn-vulkan.exe'
    'Git for Windows' = 'C:\Program Files\Git\cmd\git.exe'
    'BtabJsonTool' = 'C:\Users\Sero\BBReborneDIYTool\Tools\BtabJsonTool\bin\Release\net9.0\BtabJsonTool.exe'
    'BtlJsonTool' = 'C:\Users\Sero\BBReborneDIYTool\Tools\BtlJsonTool\bin\Release\net9.0\BtlJsonTool.exe'
    'BtpbJsonTool' = 'C:\Users\Sero\BBReborneDIYTool\Tools\BtpbJsonTool\bin\Release\net9.0\BtpbJsonTool.exe'
    'DCXTool' = 'C:\Users\Sero\BBReborneDIYTool\Tools\DCXTool\bin\Release\net9.0\DCXTool.exe'
    'FlverJsonTool' = 'C:\Users\Sero\BBReborneDIYTool\Tools\FlverJsonTool\bin\Release\net9.0\FlverJsonTool.exe'
    'FxrJsonTool' = 'C:\Users\Sero\BBReborneDIYTool\Tools\FxrJsonTool\bin\Release\net9.0\FxrJsonTool.exe'
    'MsbbJsonTool' = 'C:\Users\Sero\BBReborneDIYTool\Tools\MsbbJsonTool\bin\Release\net9.0\MsbbJsonTool.exe'
    'NvaJsonTool' = 'C:\Users\Sero\BBReborneDIYTool\Tools\NvaJsonTool\bin\Release\net9.0\NvaJsonTool.exe'
}
