# BB Reborne DIY Tool
# Copyright (C) 2026 Greg Pitta
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# See the LICENSE file for details.

<#
    05_Mapfiles_BBReborne_Param.ps1

    BBReborne map-tab wrapper around the original GParam XML patch applier.

    It applies XML patches generated by 05b_Mapfiles_BBReborne_Param_Development.ps1
    to original *.gparambnd.dcx archives, then repacks them with WitchyBND.

    Expected patch target paths look like:
        m24_02_0000-gparambnd-dcx/m24_02_0000.gparam.xml
        m24_02_0000-gparambnd-dcx/m24_02_0100.gparam.xml

    That maps back to:
        m24_02_0000.gparambnd.dcx

    If the original archive was under a subfolder, the same relative structure is
    preserved:
        drawparam/m24_02_0000.gparambnd.dcx
        drawparam/m24_02_0000-gparambnd-dcx/m24_02_0000.gparam.xml

    Notes:
    Tool defaults for M21:
    - PatchDir defaults to <ProjectRoot>\Diffs\param\drawparam.
    - OriginalDir defaults to <GameRoot>\param\drawparam.
    - OutputDir defaults to <OutputRoot>\BBReborne_param\param\drawparam.
    - MapCode M21 filters patches to ParamPrefix m21_.

    Important:
    - This script intentionally operates only on *.gparambnd.dcx archives.
      Loose *.gparam.dcx files in drawparam are ignored by the matcher.
    - PatchDir is read-only input.
    - OriginalDir is read-only input.
    - OutputDir receives patched/repacked archives and scratch work.
    - Only the safe scratch folder leaf named by -WorkDirName may be deleted/recreated.
#>

[CmdletBinding()]
param(
    # BBReborne DIY Tool / GUI-level inputs.
    [string]$ToolPathsPs1 = "",
    [string]$GameRoot = "",
    [string]$OutputRoot = "",
    [string]$LogDir = "",
    [string]$MapCode = "",
    [string]$MapFolder = "",
    [string]$ParamPrefix = "",

    # Original script inputs. Kept compatible with the known working manual call.
    [string]$PatchDir = "",
    [string]$OriginalDir = "",
    [string]$OutputDir = "",
    [string]$WitchyBND = "",

    [string]$GitExe = "git",

    [int]$WitchyBatchSize = 50,

    [switch]$RecurseOriginal = $true,

    [ValidateSet("AutoDedup","FinalRepoOnly","StagedFilesOnly","DirectPatchDirOnly")]
    [string]$PatchSearchMode = "AutoDedup",

    [switch]$PreferThreeWay,

    [switch]$DryRun,
    [switch]$KeepWork,

    [string]$WorkDirName = "_gparam_patch_apply_work"
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"
$global:PSNativeCommandUseErrorActionPreference = $false
$global:PSNativeCommandArgumentPassing = "Standard"

if ($PSVersionTable.PSVersion.Major -lt 7) {
    throw "This script requires PowerShell 7+. Run it with pwsh."
}

function Assert-File([string]$Path, [string]$Name) {
    if (-not (Test-Path -LiteralPath $Path -PathType Leaf)) { throw "$Name not found: $Path" }
}

function Assert-Dir([string]$Path, [string]$Name) {
    if (-not (Test-Path -LiteralPath $Path -PathType Container)) { throw "$Name not found: $Path" }
}

function Ensure-Dir([string]$Path) {
    if (-not (Test-Path -LiteralPath $Path -PathType Container)) {
        New-Item -ItemType Directory -Path $Path -Force | Out-Null
    }
}

function Assert-SafeScratchFolder([string]$Path, [string]$ExpectedLeaf) {
    $full = [IO.Path]::GetFullPath($Path).TrimEnd('\', '/')
    $leaf = [IO.Path]::GetFileName($full)
    if ($leaf -ne $ExpectedLeaf) {
        throw "Refusing to clean scratch folder because its leaf is not '$ExpectedLeaf': $full"
    }
}

function Reset-ScratchFolder([string]$Path, [string]$ExpectedLeaf) {
    Assert-SafeScratchFolder -Path $Path -ExpectedLeaf $ExpectedLeaf
    if (Test-Path -LiteralPath $Path -PathType Container) {
        Remove-Item -LiteralPath $Path -Recurse -Force
    }
    Ensure-Dir $Path
}

function Test-IsSameOrUnderPath([string]$Child, [string]$Parent) {
    $childFull = [IO.Path]::GetFullPath($Child).TrimEnd('\', '/')
    $parentFull = [IO.Path]::GetFullPath($Parent).TrimEnd('\', '/')

    if ($childFull.Equals($parentFull, [StringComparison]::OrdinalIgnoreCase)) { return $true }

    return (
        $childFull.StartsWith($parentFull + [IO.Path]::DirectorySeparatorChar, [StringComparison]::OrdinalIgnoreCase) -or
        $childFull.StartsWith($parentFull + [IO.Path]::AltDirectorySeparatorChar, [StringComparison]::OrdinalIgnoreCase)
    )
}

function ConvertTo-PosixPath([string]$Path) {
    return (($Path -replace '\\','/').TrimStart('/'))
}

function ConvertTo-WindowsRelPath([string]$Path) {
    return (($Path -replace '/', '\').TrimStart('\'))
}


function Convert-MapCodeToMapFolder([string]$Code) {
    $clean = ($Code.Trim()).ToLowerInvariant()
    if ($clean -match '^m\d{2}_\d{2}_\d{2}_\d{2}$') { return $clean }
    if ($clean -match '^m\d{2}$') { return ("{0}_00_00_00" -f $clean) }
    throw "Unsupported MapCode '$Code'. Expected values like M21 or m21_00_00_00."
}

function Get-BBReborneProjectRoot([string]$ToolPathsFile) {
    if (-not [string]::IsNullOrWhiteSpace($ToolPathsFile)) {
        $toolPathsFull = [IO.Path]::GetFullPath($ToolPathsFile)
        $toolRootFromFile = Split-Path -Parent $toolPathsFull
        if ((Split-Path -Leaf $toolRootFromFile) -ieq 'Tools') {
            return (Split-Path -Parent $toolRootFromFile)
        }
    }

    # This script is expected under <ProjectRoot>\Scripts\Mapfiles.
    $scriptsRoot = Split-Path -Parent $PSScriptRoot
    return (Split-Path -Parent $scriptsRoot)
}

function Test-IsGeneratedScratchPath([string]$Path) {
    $p = ([IO.Path]::GetFullPath($Path) -replace '\\','/')
    return ($p -match '(^|/)(_gparam_patch_apply_work|_gparam_patch_work|_patch_apply_work|_patch_work|_normalized_patches)(/|$)')
}

function Get-PatchSelectionRank([string]$PatchPath, [string]$Root) {
    # Lower rank wins. Prefer final repository layout over staged files\ layout.
    $rel = ([IO.Path]::GetRelativePath($Root, $PatchPath) -replace '\\','/')
    if ($rel -match '(^|/)(_gparam_patch_apply_work|_gparam_patch_work|_patch_apply_work|_patch_work|_normalized_patches)(/|$)') { return 1000 }
    if ($rel -match '(^|/)files/') { return 20 }
    if ($rel -match '(^|/)_patches/') { return 10 }
    if ($rel -match '/_patches/') { return 10 }
    return 50
}

function Get-APathFromPatchHeader([string]$PatchPath) {
    $lines = Get-Content -LiteralPath $PatchPath -TotalCount 80
    foreach ($line in $lines) {
        if ($line -notmatch '^diff --git\s+') { continue }

        $m = [regex]::Match($line, '^diff --git\s+("([^"]+)"|(\S+))\s+("([^"]+)"|(\S+))\s*$')
        if (-not $m.Success) { return $null }
        if ($m.Groups[2].Success) { return $m.Groups[2].Value }
        return $m.Groups[3].Value
    }

    return $null
}

function Get-XmlRelFromPatch([string]$PatchPath) {
    $aToken = Get-APathFromPatchHeader $PatchPath
    if (-not $aToken) { return $null }

    $p = $aToken -replace '\\','/'
    $p = $p -replace '^(a|b)/',''
    return $p
}

function Get-GparamArchiveInfoFromXmlRel([string]$XmlRel) {
    $posix = ConvertTo-PosixPath $XmlRel
    $parts = @($posix -split '/' | Where-Object { -not [string]::IsNullOrWhiteSpace($_) })

    for ($i = 0; $i -lt $parts.Count; $i++) {
        if ($parts[$i] -match '(?i)-gparambnd-dcx$') {
            $folderLeaf = $parts[$i]
            $archiveLeaf = ($folderLeaf -replace '(?i)-gparambnd-dcx$', '.gparambnd.dcx')

            $prefix = @()
            if ($i -gt 0) { $prefix = @($parts[0..($i - 1)]) }

            $archiveParts = @($prefix + @($archiveLeaf))
            $folderParts  = @($prefix + @($folderLeaf))

            return [pscustomobject]@{
                XmlRelPosix = $posix
                ArchiveRelPosix = [string]::Join('/', $archiveParts)
                ArchiveRelWin = ConvertTo-WindowsRelPath ([string]::Join('/', $archiveParts))
                ExtractFolderRelPosix = [string]::Join('/', $folderParts)
                ExtractFolderRelWin = ConvertTo-WindowsRelPath ([string]::Join('/', $folderParts))
                ExtractFolderLeaf = $folderLeaf
                ArchiveLeaf = $archiveLeaf
            }
        }
    }

    throw "Could not infer .gparambnd.dcx archive from patch target path: $XmlRel"
}

function Find-GparamXmlPatchFiles {
    param(
        [Parameter(Mandatory=$true)][string]$Root,
        [ValidateSet("AutoDedup","FinalRepoOnly","StagedFilesOnly","DirectPatchDirOnly")]
        [string]$Mode = "AutoDedup"
    )

    $rootFull = [IO.Path]::GetFullPath($Root)
    $found = [System.Collections.Generic.List[object]]::new()

    function Add-PatchesFromDir([string]$Dir, [bool]$Recursive) {
        if (-not (Test-Path -LiteralPath $Dir -PathType Container)) { return }

        $gci = @{ LiteralPath=$Dir; File=$true; Filter="*.gparam.xml.patch"; ErrorAction="SilentlyContinue" }
        if ($Recursive) { $gci.Recurse = $true }

        Get-ChildItem @gci |
            Where-Object { $_.Length -gt 0 } |
            Where-Object { -not (Test-IsGeneratedScratchPath $_.FullName) } |
            ForEach-Object { [void]$found.Add($_) }
    }

    function Add-FinalRepoPatchesFromRoot([string]$Dir) {
        if (-not (Test-Path -LiteralPath $Dir -PathType Container)) { return }

        if ((Split-Path -Leaf $Dir) -eq "_patches") {
            Add-PatchesFromDir -Dir $Dir -Recursive $false
            return
        }

        $childPatches = Join-Path $Dir "_patches"
        if (Test-Path -LiteralPath $childPatches -PathType Container) {
            Add-PatchesFromDir -Dir $childPatches -Recursive $false
        }

        Get-ChildItem -LiteralPath $Dir -Directory -Filter "_patches" -Recurse -ErrorAction SilentlyContinue |
            Where-Object {
                $rel = ([IO.Path]::GetRelativePath($Dir, $_.FullName) -replace '\\','/')
                $rel -notmatch '(^|/)files/'
            } |
            ForEach-Object {
                Add-PatchesFromDir -Dir $_.FullName -Recursive $false
            }
    }

    function Add-StagedFilesPatchesFromRoot([string]$Dir) {
        if (-not (Test-Path -LiteralPath $Dir -PathType Container)) { return }

        $leaf = Split-Path -Leaf $Dir
        $filesRoot = if ($leaf -eq "files") { $Dir } else { Join-Path $Dir "files" }

        if (Test-Path -LiteralPath $filesRoot -PathType Container) {
            Add-PatchesFromDir -Dir $filesRoot -Recursive $true
        }
    }

    switch ($Mode) {
        "DirectPatchDirOnly" {
            Add-PatchesFromDir -Dir $rootFull -Recursive $false
        }

        "FinalRepoOnly" {
            Add-FinalRepoPatchesFromRoot -Dir $rootFull
        }

        "StagedFilesOnly" {
            Add-StagedFilesPatchesFromRoot -Dir $rootFull
        }

        "AutoDedup" {
            Add-FinalRepoPatchesFromRoot -Dir $rootFull
            Add-StagedFilesPatchesFromRoot -Dir $rootFull

            # Accept older _patches\files layout.
            if ((Split-Path -Leaf $rootFull) -eq "_patches") {
                Add-PatchesFromDir -Dir (Join-Path $rootFull "files") -Recursive $true
            }

            $childPatches = Join-Path $rootFull "_patches"
            if (Test-Path -LiteralPath $childPatches -PathType Container) {
                Add-PatchesFromDir -Dir (Join-Path $childPatches "files") -Recursive $true
            }

            # Fallback for hand-copied direct patch files.
            if ($found.Count -eq 0) {
                Add-PatchesFromDir -Dir $rootFull -Recursive $true
            }
        }
    }

    return @($found | Sort-Object FullName -Unique)
}

function Invoke-NativeChecked {
    param(
        [Parameter(Mandatory=$true)][string]$Exe,
        [Parameter(Mandatory=$true)][string[]]$Arguments,
        [string]$WorkingDirectory = "",
        [int[]]$AllowedExitCodes = @(0),
        [string]$Label = "native command"
    )

    if (-not [string]::IsNullOrWhiteSpace($WorkingDirectory)) { Push-Location -LiteralPath $WorkingDirectory }
    try {
        & $Exe @Arguments | Out-Null
        $code = $LASTEXITCODE
        if ($AllowedExitCodes -notcontains $code) {
            throw "$Label failed with exit code $code. Command: $Exe $($Arguments -join ' ')"
        }
    }
    finally {
        if (-not [string]::IsNullOrWhiteSpace($WorkingDirectory)) { Pop-Location }
    }
}

function Invoke-WitchyBatchSimple {
    param(
        [Parameter(Mandatory=$true)][string]$Exe,
        [Parameter(Mandatory=$true)][string[]]$Paths,
        [int]$BatchSize = 50,
        [string]$Label = "WitchyBND"
    )

    $total = $Paths.Count
    if ($total -eq 0) { return }

    for ($start = 0; $start -lt $total; $start += $BatchSize) {
        $endExclusive = [Math]::Min($start + $BatchSize, $total)
        $batch = @($Paths[$start..($endExclusive - 1)])
        $batchNum = [int]([Math]::Floor($start / $BatchSize) + 1)
        Write-Host ("  {0} batch {1}: files {2}-{3} ({4} files)" -f $Label, $batchNum, ($start + 1), $endExclusive, $batch.Count)
        Invoke-NativeChecked -Exe $Exe -Arguments $batch -Label "$Label batch $batchNum"
    }
}

function Invoke-GitApplyPatch {
    param(
        [Parameter(Mandatory=$true)][string]$GitExe,
        [Parameter(Mandatory=$true)][string]$PatchPath,
        [Parameter(Mandatory=$true)][string]$WorkRoot,
        [Parameter(Mandatory=$true)][string]$XmlRelPosix,
        [switch]$PreferThreeWay
    )

    $xmlRelWin = ConvertTo-WindowsRelPath $XmlRelPosix
    $targetXml = Join-Path $WorkRoot $xmlRelWin

    if (-not (Test-Path -LiteralPath $targetXml -PathType Leaf)) {
        throw "Patch target XML is missing: $targetXml"
    }

    $backupXml = "$targetXml.__prepatch__"
    Copy-Item -LiteralPath $targetXml -Destination $backupXml -Force

    if ($PreferThreeWay) {
        $attempts = @(
            [pscustomobject]@{ Name="3way"; Args=@("apply", "-p1", "--3way", "--recount", "--whitespace=nowarn", "--", $PatchPath) },
            [pscustomobject]@{ Name="strict"; Args=@("apply", "-p1", "--recount", "--whitespace=nowarn", "--", $PatchPath) },
            [pscustomobject]@{ Name="ignore-space"; Args=@("apply", "-p1", "--recount", "--whitespace=nowarn", "--ignore-space-change", "--ignore-whitespace", "--", $PatchPath) },
            [pscustomobject]@{ Name="reject-diagnostic"; Args=@("apply", "-p1", "--reject", "--recount", "--whitespace=nowarn", "--", $PatchPath) }
        )
    }
    else {
        $attempts = @(
            [pscustomobject]@{ Name="strict"; Args=@("apply", "-p1", "--recount", "--whitespace=nowarn", "--", $PatchPath) },
            [pscustomobject]@{ Name="ignore-space"; Args=@("apply", "-p1", "--recount", "--whitespace=nowarn", "--ignore-space-change", "--ignore-whitespace", "--", $PatchPath) },
            [pscustomobject]@{ Name="3way"; Args=@("apply", "-p1", "--3way", "--recount", "--whitespace=nowarn", "--", $PatchPath) },
            [pscustomobject]@{ Name="reject-diagnostic"; Args=@("apply", "-p1", "--reject", "--recount", "--whitespace=nowarn", "--", $PatchPath) }
        )
    }

    $lastExit = $null
    $lastFirstLine = ""
    $lastAttempt = ""

    Push-Location -LiteralPath $WorkRoot
    try {
        foreach ($attempt in $attempts) {
            Copy-Item -LiteralPath $backupXml -Destination $targetXml -Force

            $oldRejects = @(Get-ChildItem -LiteralPath $WorkRoot -Recurse -File -Filter "*.rej" -ErrorAction SilentlyContinue)
            foreach ($rej in $oldRejects) { Remove-Item -LiteralPath $rej.FullName -Force -ErrorAction SilentlyContinue }

            $out = @(& $GitExe @($attempt.Args) 2>&1)
            $code = $LASTEXITCODE

            $lastExit = $code
            $lastFirstLine = (($out | Select-Object -First 1) -join "")
            $lastAttempt = $attempt.Name

            if ($code -eq 0 -and $attempt.Name -ne "reject-diagnostic") {
                Remove-Item -LiteralPath $backupXml -Force -ErrorAction SilentlyContinue
                return [pscustomobject]@{
                    Ok = $true
                    XmlRel = $XmlRelPosix
                    PatchPath = $PatchPath
                    Attempt = $attempt.Name
                    Message = ""
                    RejectFiles = ""
                }
            }
        }
    }
    finally {
        Pop-Location
    }

    Copy-Item -LiteralPath $backupXml -Destination $targetXml -Force
    Remove-Item -LiteralPath $backupXml -Force -ErrorAction SilentlyContinue

    $rejects = @(Get-ChildItem -LiteralPath $WorkRoot -Recurse -File -Filter "*.rej" -ErrorAction SilentlyContinue | ForEach-Object { $_.FullName })

    return [pscustomobject]@{
        Ok = $false
        XmlRel = $XmlRelPosix
        PatchPath = $PatchPath
        Attempt = $lastAttempt
        Message = "git apply failed. LastAttempt=$lastAttempt Exit=$lastExit Message=$lastFirstLine"
        RejectFiles = ($rejects -join ";")
    }
}

$timer = [Diagnostics.Stopwatch]::StartNew()
$completed = $false
$hadFailure = $false

# ------------------------------------------------------------
# Resolve optional BBReborne tool-level inputs.
# ------------------------------------------------------------
if (-not [string]::IsNullOrWhiteSpace($ToolPathsPs1)) {
    Assert-File $ToolPathsPs1 "ToolPathsPs1"
    . $ToolPathsPs1
}

$projectRoot = Get-BBReborneProjectRoot -ToolPathsFile $ToolPathsPs1

if ([string]::IsNullOrWhiteSpace($MapFolder) -and -not [string]::IsNullOrWhiteSpace($MapCode)) {
    $MapFolder = Convert-MapCodeToMapFolder $MapCode
}
if ([string]::IsNullOrWhiteSpace($MapCode) -and -not [string]::IsNullOrWhiteSpace($MapFolder)) {
    $MapCode = (($MapFolder -split '_')[0]).ToUpperInvariant()
}
if ([string]::IsNullOrWhiteSpace($ParamPrefix) -and -not [string]::IsNullOrWhiteSpace($MapFolder)) {
    $ParamPrefix = (($MapFolder -split '_')[0]).ToLowerInvariant() + '_'
}
if ([string]::IsNullOrWhiteSpace($ParamPrefix) -and -not [string]::IsNullOrWhiteSpace($MapCode)) {
    $ParamPrefix = ($MapCode.Trim()).ToLowerInvariant() + '_'
}

if ([string]::IsNullOrWhiteSpace($GameRoot) -and (Test-Path variable:BBR_GameRoot)) { $GameRoot = $BBR_GameRoot }
if ([string]::IsNullOrWhiteSpace($OutputRoot) -and (Test-Path variable:BBR_OutputRoot)) { $OutputRoot = $BBR_OutputRoot }

# GParam patching uses WitchyBND v2.14.4.5.
if ([string]::IsNullOrWhiteSpace($WitchyBND) -and (Test-Path variable:BBR_WitchyBND_v2_14_4_5)) { $WitchyBND = $BBR_WitchyBND_v2_14_4_5 }
if (($GitExe -eq "git" -or [string]::IsNullOrWhiteSpace($GitExe)) -and (Test-Path variable:BBR_GitExe) -and -not [string]::IsNullOrWhiteSpace($BBR_GitExe)) { $GitExe = $BBR_GitExe }

if ([string]::IsNullOrWhiteSpace($PatchDir)) {
    $PatchDir = Join-Path (Join-Path (Join-Path $projectRoot 'Diffs') 'param') 'drawparam'
}
if ([string]::IsNullOrWhiteSpace($OriginalDir)) {
    if ([string]::IsNullOrWhiteSpace($GameRoot)) { throw 'GameRoot is required when OriginalDir is not provided.' }
    $OriginalDir = Join-Path (Join-Path $GameRoot 'param') 'drawparam'
}
if ([string]::IsNullOrWhiteSpace($OutputDir)) {
    if ([string]::IsNullOrWhiteSpace($OutputRoot)) { throw 'OutputRoot is required when OutputDir is not provided.' }
    $OutputDir = Join-Path (Join-Path (Join-Path $OutputRoot 'BBReborne_param') 'param') 'drawparam'
}

foreach ($required in @(
    [pscustomobject]@{ Name='PatchDir'; Value=$PatchDir },
    [pscustomobject]@{ Name='OriginalDir'; Value=$OriginalDir },
    [pscustomobject]@{ Name='OutputDir'; Value=$OutputDir },
    [pscustomobject]@{ Name='WitchyBND'; Value=$WitchyBND }
)) {
    if ([string]::IsNullOrWhiteSpace([string]$required.Value)) {
        throw "$($required.Name) is required. Pass it directly or pass ToolPathsPs1/GameRoot/OutputRoot/MapCode so it can be resolved."
    }
}

if (-not [string]::IsNullOrWhiteSpace($MapCode)) { Write-Host ("MapCode:     {0}" -f $MapCode) }
if (-not [string]::IsNullOrWhiteSpace($MapFolder)) { Write-Host ("MapFolder:   {0}" -f $MapFolder) }
if (-not [string]::IsNullOrWhiteSpace($ParamPrefix)) { Write-Host ("ParamPrefix: {0}" -f $ParamPrefix) }
Write-Host ("ProjectRoot: {0}" -f $projectRoot)

$patchRoot = [IO.Path]::GetFullPath($PatchDir)
$origRoot  = [IO.Path]::GetFullPath($OriginalDir)
$outRoot   = [IO.Path]::GetFullPath($OutputDir)

Assert-Dir $patchRoot "PatchDir"
Assert-Dir $origRoot "OriginalDir"
Assert-File $WitchyBND "WitchyBND"

if (Test-IsSameOrUnderPath -Child $outRoot -Parent $patchRoot) {
    throw "OutputDir must not be the PatchDir or inside PatchDir. PatchDir is an input patch repository: $patchRoot"
}
if (Test-IsSameOrUnderPath -Child $outRoot -Parent $origRoot) {
    throw "OutputDir must not be the OriginalDir or inside OriginalDir. This safe applier does not patch in place: $origRoot"
}

$workRoot = Join-Path $outRoot $WorkDirName
if ([string]::IsNullOrWhiteSpace($LogDir)) {
    if (-not [string]::IsNullOrWhiteSpace($OutputRoot)) {
        $LogDir = Join-Path (Join-Path (Join-Path $OutputRoot '_logs') 'mapfiles') 'param'
    }
    else {
        $LogDir = Join-Path $outRoot '_logs'
    }
}
$manifestRoot = [IO.Path]::GetFullPath($LogDir)

try {
    Write-Host ("PatchDir:        {0}" -f $patchRoot)
    Write-Host ("OriginalDir:     {0}" -f $origRoot)
    Write-Host ("OutputDir:       {0}" -f $outRoot)
    Write-Host ("WorkDir:         {0}" -f $workRoot)
    Write-Host ("LogDir:          {0}" -f $manifestRoot)
    Write-Host ("PatchSearchMode: {0}" -f $PatchSearchMode)
    if ($PreferThreeWay) { Write-Host "PreferThreeWay:  enabled" -ForegroundColor Yellow }

    $patchCandidates = @(Find-GparamXmlPatchFiles -Root $patchRoot -Mode $PatchSearchMode)

    if (-not [string]::IsNullOrWhiteSpace($ParamPrefix)) {
        $prefixLower = $ParamPrefix.ToLowerInvariant()
        $beforeFilterCount = $patchCandidates.Count
        $patchCandidates = @($patchCandidates | Where-Object {
            $xmlRel = Get-XmlRelFromPatch $_.FullName
            $match = $false
            if ($xmlRel) {
                $xmlNorm = (ConvertTo-PosixPath $xmlRel).ToLowerInvariant()
                if ($xmlNorm.StartsWith($prefixLower)) { $match = $true }
            }
            if (-not $match) {
                $leafLower = $_.Name.ToLowerInvariant()
                $fullLower = ($_.FullName -replace '\\','/').ToLowerInvariant()
                if ($leafLower.StartsWith($prefixLower) -or $fullLower.Contains('/' + $prefixLower)) { $match = $true }
            }
            $match
        })
        Write-Host ("Filtered GParam XML patches by ParamPrefix '{0}': {1} -> {2}" -f $ParamPrefix, $beforeFilterCount, $patchCandidates.Count)
    }

    Write-Host ("Found {0} non-empty GParam XML patch candidate file(s)." -f $patchCandidates.Count)
    if ($patchCandidates.Count -eq 0) { Write-Host "Nothing to do."; return }

    if ($PatchSearchMode -eq "AutoDedup") {
        $patchByXmlRel = @{}
        $duplicateRows = [System.Collections.Generic.List[object]]::new()

        foreach ($pf in $patchCandidates) {
            $xmlRel = Get-XmlRelFromPatch $pf.FullName
            if (-not $xmlRel) {
                $xmlRel = "__unparsed__/{0}" -f $pf.FullName.ToLowerInvariant()
            }

            if (-not $patchByXmlRel.ContainsKey($xmlRel)) {
                $patchByXmlRel[$xmlRel] = [System.Collections.Generic.List[object]]::new()
            }
            [void]$patchByXmlRel[$xmlRel].Add($pf)
        }

        $selectedPatches = [System.Collections.Generic.List[object]]::new()

        foreach ($xmlRel in ($patchByXmlRel.Keys | Sort-Object)) {
            $group = @($patchByXmlRel[$xmlRel])
            if ($group.Count -gt 1 -and -not $xmlRel.StartsWith("__unparsed__/")) {
                $winner = @($group | Sort-Object @{ Expression = { Get-PatchSelectionRank -PatchPath $_.FullName -Root $patchRoot } }, FullName | Select-Object -First 1)[0]

                foreach ($dupe in $group) {
                    [void]$duplicateRows.Add([pscustomobject]@{
                        XmlRel = $xmlRel
                        Selected = ($dupe.FullName -eq $winner.FullName)
                        Rank = Get-PatchSelectionRank -PatchPath $dupe.FullName -Root $patchRoot
                        PatchPath = $dupe.FullName
                    })
                }

                [void]$selectedPatches.Add($winner)
            }
            else {
                foreach ($pf in $group) { [void]$selectedPatches.Add($pf) }
            }
        }

        $patches = @($selectedPatches | Sort-Object FullName)

        if ($duplicateRows.Count -gt 0) {
            Write-Host ("  De-duplicated {0} duplicate patch candidate entries. Using {1} unique patch target(s)." -f $duplicateRows.Count, $patches.Count) -ForegroundColor Yellow
            $dupePreview = @($duplicateRows | Where-Object { -not $_.Selected } | Select-Object -First 12)
            foreach ($d in $dupePreview) {
                Write-Host ("    SKIP duplicate: {0}" -f $d.PatchPath) -ForegroundColor DarkYellow
            }
        }
    }
    else {
        $patches = @($patchCandidates | Sort-Object FullName -Unique)
    }

    Write-Host ("Using {0} GParam XML patch file(s)." -f $patches.Count)

    $jobs = [System.Collections.Generic.List[object]]::new()
    $matchRows = [System.Collections.Generic.List[object]]::new()

    foreach ($p in $patches) {
        $xmlRel = Get-XmlRelFromPatch $p.FullName
        if (-not $xmlRel) {
            [void]$matchRows.Add([pscustomobject]@{
                PatchPath = $p.FullName
                XmlRel = ""
                ArchiveRel = ""
                Status = "Skip"
                Message = "Could not parse diff --git header"
            })
            continue
        }

        $info = Get-GparamArchiveInfoFromXmlRel $xmlRel
        $origArchive = Join-Path $origRoot $info.ArchiveRelWin

        if (-not (Test-Path -LiteralPath $origArchive -PathType Leaf)) {
            [void]$matchRows.Add([pscustomobject]@{
                PatchPath = $p.FullName
                XmlRel = $info.XmlRelPosix
                ArchiveRel = $info.ArchiveRelPosix
                Status = "MissingOriginal"
                Message = "Original archive not found: $origArchive"
            })
            continue
        }

        [void]$jobs.Add([pscustomobject]@{
            PatchPath = $p.FullName
            PatchLeaf = $p.Name
            XmlRelPosix = $info.XmlRelPosix
            XmlRelWin = ConvertTo-WindowsRelPath $info.XmlRelPosix
            ArchiveRelPosix = $info.ArchiveRelPosix
            ArchiveRelWin = $info.ArchiveRelWin
            ExtractFolderRelPosix = $info.ExtractFolderRelPosix
            ExtractFolderRelWin = $info.ExtractFolderRelWin
            OrigArchive = $origArchive
        })

        [void]$matchRows.Add([pscustomobject]@{
            PatchPath = $p.FullName
            XmlRel = $info.XmlRelPosix
            ArchiveRel = $info.ArchiveRelPosix
            Status = "Matched"
            Message = ""
        })
    }

    Write-Host ("Matched patches: {0} / {1}" -f $jobs.Count, $patches.Count)

    if ($DryRun) {
        Write-Host "DRYRUN: stopping after patch/original matching."
        $completed = $true
        return
    }

    Ensure-Dir $outRoot
    Ensure-Dir $manifestRoot
    Reset-ScratchFolder -Path $workRoot -ExpectedLeaf $WorkDirName

    $matchManifest = Join-Path $manifestRoot "gparam_patch_match_manifest.csv"
    $matchRows | Export-Csv -LiteralPath $matchManifest -NoTypeInformation -Encoding UTF8

    if ($jobs.Count -eq 0) {
        throw "No patches matched original .gparambnd.dcx files. See: $matchManifest"
    }

    $failedMatches = @($matchRows | Where-Object { $_.Status -ne "Matched" })
    if ($failedMatches.Count -gt 0) {
        Write-Host ("  WARN: {0} patch(es) did not match originals. See: {1}" -f $failedMatches.Count, $matchManifest) -ForegroundColor Yellow
    }

    Write-Host ""
    Write-Host "Stage #1: copying original GParam binder DCX files into work folder..."

    $archives = @($jobs | Group-Object ArchiveRelPosix | Sort-Object Name)
    foreach ($grp in $archives) {
        $first = $grp.Group[0]
        $workArchive = Join-Path $workRoot $first.ArchiveRelWin
        Ensure-Dir (Split-Path -Parent $workArchive)
        Copy-Item -LiteralPath $first.OrigArchive -Destination $workArchive -Force
    }

    Write-Host ""
    Write-Host ("Stage #2: decompressing GParam binders with WitchyBND, batchSize={0}..." -f $WitchyBatchSize)

    $archivePaths = @($archives | ForEach-Object { Join-Path $workRoot $_.Group[0].ArchiveRelWin })
    Invoke-WitchyBatchSimple -Exe $WitchyBND -Paths $archivePaths -BatchSize $WitchyBatchSize -Label "WitchyBND decompress"

    $missingExtracts = @()
    foreach ($grp in $archives) {
        $first = $grp.Group[0]
        $extractPath = Join-Path $workRoot $first.ExtractFolderRelWin
        if (-not (Test-Path -LiteralPath $extractPath -PathType Container)) {
            $missingExtracts += [pscustomobject]@{
                ArchiveRel = $first.ArchiveRelPosix
                ExtractFolder = $extractPath
            }
        }
    }

    if ($missingExtracts.Count -gt 0) {
        $missingCsv = Join-Path $outRoot "missing_gparam_extract_folders.csv"
        $missingExtracts | Export-Csv -LiteralPath $missingCsv -NoTypeInformation -Encoding UTF8
        throw "Some GParam archives did not extract to expected folders. See: $missingCsv"
    }

    Write-Host ""
    Write-Host "Stage #3: applying XML patches..."

    $applyRows = [System.Collections.Generic.List[object]]::new()
    $n = 0
    foreach ($j in $jobs) {
        $n++
        Write-Progress -Activity "Apply GParam XML patches" -Status ("{0}/{1}: {2}" -f $n, $jobs.Count, $j.PatchLeaf) -PercentComplete ([int](100.0 * $n / $jobs.Count))

        $row = Invoke-GitApplyPatch `
            -GitExe $GitExe `
            -PatchPath $j.PatchPath `
            -WorkRoot $workRoot `
            -XmlRelPosix $j.XmlRelPosix `
            -PreferThreeWay:$PreferThreeWay

        $row | Add-Member -NotePropertyName ArchiveRel -NotePropertyValue $j.ArchiveRelPosix -Force
        [void]$applyRows.Add($row)

        if (-not $row.Ok) {
            Write-Host ("  FAIL: {0}" -f $j.PatchLeaf) -ForegroundColor Red
            Write-Host ("        {0}" -f $row.Message) -ForegroundColor Red
            if ($row.RejectFiles) { Write-Host ("        Rejects: {0}" -f $row.RejectFiles) -ForegroundColor Red }
        }
    }
    Write-Progress -Activity "Apply GParam XML patches" -Completed

    $applyManifest = Join-Path $manifestRoot "gparam_patch_apply_manifest.csv"
    $applyRows | Export-Csv -LiteralPath $applyManifest -NoTypeInformation -Encoding UTF8

    $failedApply = @($applyRows | Where-Object { -not $_.Ok })
    if ($failedApply.Count -gt 0) {
        throw "Patch apply failed for $($failedApply.Count) XML patch(es). See: $applyManifest"
    }

    Write-Host ""
    Write-Host ("Stage #4: recompressing patched GParam folders with WitchyBND, batchSize={0}..." -f $WitchyBatchSize)

    $extractFolders = @($archives | ForEach-Object { Join-Path $workRoot $_.Group[0].ExtractFolderRelWin })
    Invoke-WitchyBatchSimple -Exe $WitchyBND -Paths $extractFolders -BatchSize $WitchyBatchSize -Label "WitchyBND recompress"

    $repackRows = [System.Collections.Generic.List[object]]::new()
    foreach ($grp in $archives) {
        $first = $grp.Group[0]
        $workArchive = Join-Path $workRoot $first.ArchiveRelWin
        $ok = Test-Path -LiteralPath $workArchive -PathType Leaf
        [void]$repackRows.Add([pscustomobject]@{
            ArchiveRel = $first.ArchiveRelPosix
            WorkArchive = $workArchive
            Ok = [bool]$ok
        })
    }

    $repackManifest = Join-Path $manifestRoot "gparam_repack_manifest.csv"
    $repackRows | Export-Csv -LiteralPath $repackManifest -NoTypeInformation -Encoding UTF8

    $failedRepack = @($repackRows | Where-Object { -not $_.Ok })
    if ($failedRepack.Count -gt 0) {
        throw "Repack did not produce expected archive(s). See: $repackManifest"
    }

    Write-Host ""
    Write-Host "Stage #5: writing patched GParam binder DCX files into OutputDir..."

    foreach ($grp in $archives) {
        $first = $grp.Group[0]
        $workArchive = Join-Path $workRoot $first.ArchiveRelWin
        $destArchive = Join-Path $outRoot $first.ArchiveRelWin
        Ensure-Dir (Split-Path -Parent $destArchive)
        Copy-Item -LiteralPath $workArchive -Destination $destArchive -Force
    }

    Write-Host ""
    Write-Host "================ FINAL SUMMARY ================"
    Write-Host ("Patches applied: {0}" -f $jobs.Count)
    Write-Host ("Archives rebuilt: {0}" -f $archives.Count)
    Write-Host ("PatchSearchMode: {0}" -f $PatchSearchMode)
    Write-Host ("PreferThreeWay:  {0}" -f ([bool]$PreferThreeWay))
    Write-Host ("OutputDir:       {0}" -f $outRoot)
    Write-Host ("Apply manifest:  {0}" -f $applyManifest)
    Write-Host ("Elapsed:         {0}" -f $timer.Elapsed.ToString())

    $completed = $true
}
catch {
    $hadFailure = $true
    throw
}
finally {
    Write-Host ""
    Write-Host "Stage #6: cleanup..."
    if ($DryRun) {
        Write-Host ("  DRY: would remove work folder: {0}" -f $workRoot)
    }
    elseif ($KeepWork -or $hadFailure -or -not $completed) {
        Write-Host ("  Keeping work folder: {0}" -f $workRoot)
        if ($hadFailure -or -not $completed) { Write-Host "  Kept because the run did not complete successfully." -ForegroundColor Yellow }
    }
    else {
        Assert-SafeScratchFolder -Path $workRoot -ExpectedLeaf $WorkDirName
        if (Test-Path -LiteralPath $workRoot -PathType Container) {
            Remove-Item -LiteralPath $workRoot -Recurse -Force
            Write-Host ("  Removed: {0}" -f $workRoot)
        }
    }
}
